export const COMPANY = {
  name: 'Technogig Software Solution',
  short: 'TSS',
  tagline: 'Technology + Logic = Let\'s Technogig Your Business',
  subTagline: 'A Digital Engineering & Technology Partner Deeply Invested in Your Success',
  phone: '+91-8445806095',
  email: 'hr@technogigsolution.in',
  addresses: [
    'SRS Tower, Sector 31, Faridabad, Haryana 121003',
    'Techman City, Mathura, UP',
  ],
  stats: [
    { value: 85, suffix: '+', label: 'Happy Clients' },
    { value: 100, suffix: '+', label: 'Projects Delivered' },
    { value: 10000, suffix: '+', label: 'Businesses Impacted' },
    { value: 5, suffix: '★', label: 'Average Rating' },
  ],
}

export const SERVICES = [
  {
    id: 1,
    title: 'Web Design & Development',
    icon: '🌐',
    short: 'Custom, responsive, performance-optimized websites and web apps.',
    description: 'We craft stunning, high-performance websites and web applications that captivate users and drive conversions. From landing pages to complex SaaS platforms, we build with React, Next.js, Vue, and Laravel.',
    tech: ['React', 'Next.js', 'Vue.js', 'Laravel', 'TypeScript'],
  },
  {
    id: 2,
    title: 'Mobile App Development',
    icon: '📱',
    short: 'Native & cross-platform iOS/Android apps.',
    description: 'Transform your idea into a powerful mobile experience. We develop native and cross-platform apps using Flutter and React Native, delivering smooth performance across iOS and Android.',
    tech: ['Flutter', 'React Native', 'Swift', 'Kotlin', 'Firebase'],
  },
  {
    id: 3,
    title: 'MLM Software Development',
    icon: '🔗',
    short: 'Binary, Matrix, Unilevel, Board Plan MLM systems.',
    description: 'We build robust, scalable MLM software with advanced features — Binary, Matrix, Unilevel, Board Plan, and Generation plans — complete with real-time admin dashboards and commission engines.',
    tech: ['Node.js', 'React', 'MySQL', 'Redis', 'AWS'],
  },
  {
    id: 4,
    title: 'E-Commerce Development',
    icon: '🛒',
    short: 'Full-featured online stores with payment integrations.',
    description: 'Launch your online store with confidence. We build feature-rich e-commerce platforms with seamless payment gateways, inventory management, and analytics — on Shopify, WooCommerce, or custom stacks.',
    tech: ['Shopify', 'WooCommerce', 'React', 'Stripe', 'Razorpay'],
  },
  {
    id: 5,
    title: 'CRM & HRM Software',
    icon: '👥',
    short: 'Custom CRM/HRM platforms for modern businesses.',
    description: 'Streamline your business operations with custom CRM and HRM solutions. Manage customers, leads, employees, attendance, payroll, and workflows — all in one powerful platform.',
    tech: ['React', 'Node.js', 'PostgreSQL', 'Docker', 'REST API'],
  },
  {
    id: 6,
    title: 'AI & Machine Learning',
    icon: '🤖',
    short: 'Predictive analytics, NLP, computer vision & AI automation.',
    description: 'Harness the power of artificial intelligence for your business. We deliver predictive analytics, NLP models, computer vision, recommendation engines, and AI-powered automation solutions.',
    tech: ['Python', 'TensorFlow', 'FastAPI', 'Scikit-learn', 'OpenAI'],
  },
  {
    id: 7,
    title: 'DevOps & Cloud Solutions',
    icon: '☁️',
    short: 'CI/CD pipelines, Docker/Kubernetes, AWS/GCP/Azure.',
    description: 'Accelerate delivery and scale with confidence. We design and implement CI/CD pipelines, containerize applications with Docker & Kubernetes, and manage cloud infrastructure on AWS, GCP, and Azure.',
    tech: ['Docker', 'Kubernetes', 'AWS', 'GCP', 'Terraform'],
  },
  {
    id: 8,
    title: 'Custom Software Development',
    icon: '⚙️',
    short: 'Bespoke enterprise solutions for your exact requirements.',
    description: 'When off-the-shelf software doesn\'t cut it, we build exactly what you need. Our engineers deliver bespoke enterprise solutions tailored precisely to your business processes and goals.',
    tech: ['.NET', 'Java', 'Python', 'Microservices', 'GraphQL'],
  },
]

export const PROJECTS = [
  {
    id: 1,
    title: 'Magic Coins',
    category: 'Frontend',
    description: 'A visually stunning marketing website for a cryptocurrency platform with advanced GSAP scroll animations and interactive coin visualizations.',
    tech: ['React', 'GSAP', 'Tailwind CSS'],
    image: 'https://picsum.photos/600/400?random=1',
  },
  {
    id: 2,
    title: 'LiveHood World',
    category: 'Full Stack',
    description: 'A full-stack social platform connecting professionals globally with real-time chat, job listings, and community boards built on Next.js.',
    tech: ['Next.js', 'Node.js', 'MongoDB', 'Socket.io'],
    image: 'https://picsum.photos/600/400?random=2',
  },
  {
    id: 3,
    title: 'Cake Make Bake',
    category: 'E-Commerce',
    description: 'An artisan bakery e-commerce store with custom order builder, Stripe payments, and real-time order tracking for a UK-based bakery chain.',
    tech: ['React', 'Stripe', 'Firebase', 'Tailwind'],
    image: 'https://picsum.photos/600/400?random=3',
  },
  {
    id: 4,
    title: 'RTG Associate',
    category: 'Backend',
    description: 'A data analytics dashboard for a financial advisory firm featuring interactive D3.js charts, REST API integrations, and real-time market data.',
    tech: ['Vue.js', 'D3.js', 'REST API', 'Node.js'],
    image: 'https://picsum.photos/600/400?random=4',
  },
  {
    id: 5,
    title: 'Image Studio Makeup',
    category: 'Frontend',
    description: 'A premium branding website for a luxury makeup studio featuring immersive GSAP animations, before/after sliders, and portfolio galleries.',
    tech: ['HTML/CSS', 'GSAP', 'JavaScript'],
    image: 'https://picsum.photos/600/400?random=5',
  },
  {
    id: 6,
    title: 'Apna House',
    category: 'Full Stack',
    description: 'A comprehensive real estate platform with advanced property search, virtual tours, mortgage calculator, and agent management system.',
    tech: ['Next.js', 'PostgreSQL', 'TypeScript', 'AWS S3'],
    image: 'https://picsum.photos/600/400?random=6',
  },
  {
    id: 7,
    title: 'DevPipeline Pro',
    category: 'DevOps',
    description: 'A DevOps automation platform that streamlines CI/CD workflows, Docker container orchestration, and multi-cloud deployments from a unified dashboard.',
    tech: ['Docker', 'Jenkins', 'AWS', 'Terraform'],
    image: 'https://picsum.photos/600/400?random=7',
  },
  {
    id: 8,
    title: 'HRConnect Suite',
    category: 'HRM',
    description: 'An enterprise HRM solution managing employee lifecycle, attendance tracking, payroll automation, and performance reviews for 500+ employee organizations.',
    tech: ['React', 'Node.js', 'MySQL', 'Redux'],
    image: 'https://picsum.photos/600/400?random=8',
  },
  {
    id: 9,
    title: 'SmartCRM 360',
    category: 'Backend',
    description: 'A powerful CRM platform with AI-driven lead scoring, automated sales pipelines, customer journey mapping, and revenue forecasting for B2B companies.',
    tech: ['Angular', '.NET', 'MSSQL', 'Azure'],
    image: 'https://picsum.photos/600/400?random=9',
  },
  {
    id: 10,
    title: 'TalentHire AI',
    category: 'AI & ML',
    description: 'An AI-powered recruitment platform that screens resumes, predicts candidate success, automates interviews, and reduces hiring time by 70%.',
    tech: ['Python', 'TensorFlow', 'FastAPI', 'React'],
    image: 'https://picsum.photos/600/400?random=10',
  },
  {
    id: 11,
    title: 'PredictSales',
    category: 'AI & ML',
    description: 'A predictive sales analytics tool that forecasts revenue, identifies churn risks, and provides actionable insights using machine learning models.',
    tech: ['Scikit-learn', 'Flask', 'React', 'Pandas'],
    image: 'https://picsum.photos/600/400?random=11',
  },
  {
    id: 12,
    title: 'ShopSwift',
    category: 'Mobile',
    description: 'A cross-platform mobile e-commerce app with AR try-on features, Razorpay integration, push notifications, and 50,000+ active users on launch.',
    tech: ['Flutter', 'Firebase', 'Razorpay', 'Dart'],
    image: 'https://picsum.photos/600/400?random=12',
  },
]

export const TESTIMONIALS = [
  {
    name: 'Rajesh Kumar',
    role: 'CEO',
    company: 'InnovateTech Pvt. Ltd.',
    rating: 5,
    quote: 'TSS transformed our business with their exceptional MLM software. The platform handles thousands of users flawlessly. Their team is responsive, professional, and truly understands our needs.',
  },
  {
    name: 'Sarah Thompson',
    role: 'Product Manager',
    company: 'GlobalShop Inc.',
    rating: 5,
    quote: 'Our e-commerce revenue tripled after TSS rebuilt our platform. The attention to UI details, performance optimization, and post-launch support is genuinely world-class.',
  },
  {
    name: 'Amit Sharma',
    role: 'Founder',
    company: 'FinanceEdge Solutions',
    rating: 5,
    quote: 'The analytics dashboard TSS built for us is phenomenal. Complex data visualizations, real-time updates, and a beautiful interface. Delivered on time, on budget. Highly recommend.',
  },
  {
    name: 'Priya Nair',
    role: 'CTO',
    company: 'TalentBridge HR',
    rating: 5,
    quote: 'We hired TSS for our HRM platform and couldn\'t be more satisfied. The system manages 2000+ employees seamlessly. Their AI features reduced our HR workload by 40%.',
  },
  {
    name: 'Michael Brooke',
    role: 'Director',
    company: 'CloudScale Technologies',
    rating: 5,
    quote: 'TSS handled our entire cloud migration and DevOps setup. Zero downtime, improved performance, and our infrastructure costs dropped by 35%. Outstanding engineering team.',
  },
]
